CREATE SCHEMA BRONZE;
GO

CREATE TABLE [BRONZE].[llamadas] (
    SERVICIO VARCHAR(10),
    REGISTRO VARCHAR(10),
    NUMERO_A VARCHAR(12),
    IMEI_A VARCHAR(18),
    RBS_UTILIZADA_A VARCHAR(50),
    CELDA_A VARCHAR(8),
    LATITUD_LONGITUD_A VARCHAR(50),
    NUMERO_B VARCHAR(12),
    IMEI_B VARCHAR(18),
    RBS_UTILIZADA_B VARCHAR(50),
    CELDA_B VARCHAR(8),
    LATITUD_LONGITUD_B VARCHAR(50),
    FECHA VARCHAR(10),
    DURACION VARCHAR(10)
);
GO

CREATE TABLE [BRONZE].[datos] (
    FECHA_INICIO VARCHAR(20),
    FECHA_FIN VARCHAR(20),
    NUMERO VARCHAR(12),
    IMEI VARCHAR(18),
    RBS_UTILIZADA VARCHAR(50),
    CELDA VARCHAR(8),
    LATITUD_LONGITUD VARCHAR(50),
    DATOS_SUBIDOS VARCHAR(20),
    DATOS_DESCARGADOS VARCHAR(20),
    VOLUMEN_TOTAL VARCHAR(20)
);
GO
