CREATE SCHEMA SILVER;
GO

CREATE TABLE [SILVER].[llamadas] (
    SERVICIO NVARCHAR(10),
    REGISTRO NVARCHAR(10),
    NUMERO_A NVARCHAR(12),
    IMEI_A NVARCHAR(18),
    RBS_UTILIZADA_A NVARCHAR(50),
    CELDA_A NVARCHAR(8),
    LATITUD_A DECIMAL(9,6),
    LONGITUD_A DECIMAL(9,6),
    NUMERO_B NVARCHAR(12),
    IMEI_B NVARCHAR(18),
    RBS_UTILIZADA_B NVARCHAR(50),
    CELDA_B NVARCHAR(8),
    LATITUD_B DECIMAL(9,6),
    LONGITUD_B DECIMAL(9,6),
    FECHA DATETIME,
    DURACION TIME
);
GO

CREATE TABLE [SILVER].[datos] (
    FECHA_INICIO DATETIME,
    FECHA_FIN DATETIME,
    NUMERO NVARCHAR(12),
    IMEI NVARCHAR(18),
    RBS_UTILIZADA NVARCHAR(50),
    CELDA NVARCHAR(8),
    LATITUD DECIMAL(9,6),
    LONGITUD DECIMAL(9,6),
    DATOS_SUBIDOS BIGINT,
    DATOS_DESCARGADOS BIGINT,
    VOLUMEN_TOTAL BIGINT
);
GO
